# @format

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202434812648:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-15EO8N1W2CFO4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::202434812648:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: '2022-07-29T11:14:30Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1704'
  uid: 0191490e-687d-4561-be8f-e521b5f24481
